ALTER TABLE "links" DROP CONSTRAINT "links_pkey";--> statement-breakpoint
ALTER TABLE "links" ADD COLUMN "id" integer PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "links" ADD CONSTRAINT "links_short_url_unique" UNIQUE("short_url");